[project]
name = "jax-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flax>=0.10.2",
    "ipykernel>=6.29.5",
    "jax>=0.5.0",
]
